# Generated by Django 4.2.27 on 2025-12-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='custom_payment_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='custom_payment_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='instamojo_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='payment_note',
            field=models.CharField(blank=True, help_text='Shown to client before payment', max_length=200),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='razorpay_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='upi_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payments/qr/'),
        ),
    ]
