# Generated by Django 4.2.27 on 2025-12-23 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='price_type',
        ),
        migrations.AddField(
            model_name='gig',
            name='gig_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly')], default='fixed', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gig',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gig',
            name='price',
            field=models.PositiveIntegerField(help_text='Fixed price or hourly rate'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
