# Generated by Django 4.2.27 on 2025-12-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0002_freelancerprofile_custom_payment_details_and_more'),
        ('gigs', '0002_remove_gig_price_type_gig_gig_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='delivery_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gig',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='gigs/'),
        ),
        migrations.AddField(
            model_name='gig',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='gigs/'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='freelancers.freelancerprofile'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='gig_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='gig',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gig',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
