# Generated by Django 6.0.1 on 2026-01-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_gig_delivery_days_gig_image1_gig_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
